src/components/Shared/Leaflet/index.js

New attempt at changing map tiles after #5 was dropped.
Do NOT merge yet, just for preview.
About the tiles: http://maps.stamen.com/#toner-lite/12/46.0556/14.5088
TODO:
Preview: https://deploy-preview-10--prosti-zdravniki.netlify.app/

Use toner map tiles by stamen design

---

package.json
src/components/DoctorCard/Info.js
src/pages/Doctor.js
yarn.lock

Instead of replacing " " with "-" and back
Uses https://www.npmjs.com/package/slugify
It fixes URLs for doctors with "-" in their name or surname
It is transliterating "đ" to "dj", so eg `Đorđević Stevan` gets the url `djordjevic-stevan` which might not be ideal

Properly slugify doctor names

---

src/components/Header/Drawer.js

Fix #78
1. Open any page in a narrow screen
2. Open the hamburger menu
3. Resize the page to desktop size
4. Drawer (sidebar) not visible but state is preserved. 
5. Resize to narrow.
6. Drawer visible.

Fix menu drawer stays open #78

---

src/components/Doctors/styles/index.js
src/pages/styles/Home.js

Due to infinite scroll height map height was too big.
FIX: #86. 
I guess this should be merged only if new design will not be implemented #89.

fix(Doctors): 💄 map attribution out of view

---

src/components/Filters/Search.js
src/components/Filters/styles/Search.js

before:
after:
`<input>` HTML element:
* uses full width of parent container (removed `width: 20ch` css) and
* is set to `type='search'` (https://caniuse.com/input-search) to give it a x at the end for easy clearing (not sure if there is another, more MUI-esque way to do so)

Set search input type & use full width

---

src/components/DoctorCard/index.js
src/components/Doctors/Map.js
src/components/Doctors/Markers.js
src/context/doctorsContext.js
src/services/doctors.js
src/utils/index.js

doctor.csv will no longer have "id" field
affects: #115

feat: 👽️ remove doctor id

---

src/components/DoctorCard/Shared/index.js
src/components/DoctorCard/styles/PageInfo.js

Difference is not so obvious.
before:
after:

fix: 💄 no border radius if age group not present

---

src/components/DoctorCard/Info.js
src/components/DoctorCard/styles/index.js

leave link on the title and in the menu.
Institution links can't be clicked and tooltips can't be triggered on mobile if the whole card area is clickable.

FIX: Remove card area click to go to the dr page

---

src/components/DoctorCard/Info.js
src/components/DoctorCard/PageInfo.js
src/components/Filters/ToggleDoctorType.js

fix: 🐛 filter state isn't preserved on return from

---

src/components/DoctorCard/Info/index.js
src/components/DoctorCard/PageInfo/index.js
src/components/DoctorCard/Shared/Accepts.js
src/components/DoctorCard/Shared/Tooltips.js
src/components/DoctorCard/Shared/index.js
src/components/DoctorCard/styles/PageInfo.js
src/components/DoctorCard/styles/index.js
src/services/doctors.js

Let's say this is one of many steps refactoring DoctorCard.
@bananica I've removed styled Tooltip(Changed) and created styled PageInfo.Override (combined style from InfoWrapper and Changed) 
Accepts component prop `accepts` is now string. It takes only "y" or "n". 
Does it make sense to add to date tooltip also `accepts -> rejects`?
If she is retired does she still accepts?
@miaerbus I think I fixed all browser console errors (non-boolean attributes) see: #104 
@lukarenko @stefanb are we going translate note?

Refactor tooltips

---

src/App.js
src/components/Shared/FooterInfo.js
src/const/csvURL.js
src/context/index.js
src/context/timestampsContext.js
src/hooks/useFetchTs.js
src/locales/en.json
src/locales/sl.json

Both timestamps (doctors and institutions) are available.
ATM using only doctors.
Check both languages.
What should we do with institutions ts?

feat: ✨ add timestamps

---

src/components/Doctors/MapOnlySnackbar.js
src/components/Doctors/index.js

Which colour do you prefer? Should it be blue like on list view or vice versa?
curent red filled:
second-option red:
list view current blue:

feat: ✨ add snackbar alert on mobile in map view

---

src/components/Filters/Shared/index.js
src/components/Filters/styles/Search.js

PR includes two fixes:
**Limits search component's clickable area**
before:
now:
**Add a gap to ToggleButton component, between icon and text**
before:
now:

Improve filters

---

src/components/Filters/Search.js
src/components/Filters/styles/Search.js

Some browsers showed the native clear-input button, which looks kind of nasty. 
So I removed that and added a custom clear input button

🔘 Clear search button

---

src/components/Doctors/Map.js
src/components/Doctors/Markers.js
src/pages/styles/Home.js

- Map marker cluster color should be based on the % of doctors who accept new patients
- Green 100% if all doctors accept, red none do, and 3 shades in between (25, 50, 75%)
- Round it to 25% so there's not too much shades
- Up to 25% color even if just 1 doctor accepts
- Down to 75% color even if just 1 doctor does not accept
I tried first with light text on darker cluster colors, atm all are dark, here are screenshots of both.
Comments welcome.

Map marker cluster color should be informative

---

src/components/DoctorCard/Info/index.js
src/components/DoctorCard/PageInfo/PhoneLinks.js
src/components/DoctorCard/PageInfo/WebsiteLinks.js
src/components/DoctorCard/PageInfo/index.js
src/components/DoctorCard/Shared/DoctorLinks.js
src/components/DoctorCard/Shared/Links.js
src/components/DoctorCard/Shared/PageInfoPhones.js
src/components/DoctorCard/Shared/index.js
src/components/Filters/styles/Search.js
src/components/Shared/Icons.js

before:
after:
Also fixes some browser errors (camelCase css property and some `prop-types` errors).
@mitjapotocin please check if `<Search/>` still looks the same.

Fix: multiple doctor's websites as single link

---

src/components/DoctorCard/styles/index.js

On dr's page there is no map on info card on medium devices.
before:
after:

fix: 🐛 no map at md breakpoint

---

src/components/Header/NavLinks.js
src/components/Header/SledilnikOrgLinks.jsx

Adds new component `SledilnikOrgLinks` for links pointing to `sledilnik.org/[lng]`.
FIX: #452

Fix: Not supported languages in external nav links

---

src/App.js
src/i18n.js

https://sledilnik.slack.com/archives/CV93RSH17/p1709448743246669?thread_ts=1708892539.600929&cid=CV93RSH17
Before: Our router was getting supported languages from `initOptions.fallbackLng`
After: from resources `languages` variable
https://pr-461.zdravniki.sledilnik.org/de/
https://pr-461.zdravniki.sledilnik.org/hr/
https://pr-461.zdravniki.sledilnik.org/hu/
https://pr-461.zdravniki.sledilnik.org/it/

fix: 🚑️ not fallback langs on first load redirected to 404

---

src/components/DoctorCard/PageInfo/index.js
src/components/DoctorCard/styles/PageInfo.js
src/services/doctors.js

missing langs: it, de, hu and hr.
also, fix the missing gap in the date override
before /hu
https://zdravniki.sledilnik.org/hu/gp/ahcin-novak-rosana/205431
https://pr-475.zdravniki.sledilnik.org/sl/gp/ahcin-novak-rosana/205431
after /hu

FIx: missing intl date format locales

---

src/components/DoctorCard/Info/index.js
src/components/DoctorCard/Shared/Tooltips.js
src/components/DoctorCard/Shared/index.js
src/locales/en.json
src/locales/sl.json

For `den` and `gyn` doctor type load is shown as a percentage.
Translations only for `sl` and `en` languages.

fix: ZZZS differentiates how load for gynecologists and dentists is calculated

---

src/components/Header/NavLinks.js
src/locales/sl.json
src/pages/Analytics/Cards/TaskD/FilterForm.jsx
src/pages/Analytics/Cards/TaskSpecial/chart-options.js

Changes:
- change the color for secondary y axis in "Gibanje števila neopredeljenih skozi čas" chart,
- hard coded label for "Primerjava glede na lastništvo javnega in zasebnega izvajalca" dropdown label,
- move header nav link for "Analytics" to second position

fix: minor bugs
