sledilnik/zdravniki

.dockerignore, .github/workflows/prod.yml, .github/workflows/stage.yml, .helm/values.prod.yml, .helm/values.stage.yml, Caddyfile, Dockerfile
First step, actions come tomorrow (or later today)
=> added dockerfile

src/components/Header/Languages.js, src/components/Header/NavLinks.js, src/components/Header/index.js, src/i18n.js
=> Fix lang sync

src/components/Header/Drawer.js, src/pages/About.js, src/pages/Home.js
=> FIX: #42 Mobile menu disables scrolling on content page

src/components/DoctorCard/dicts.js
=> Fix doctor card gyn chip "undefined"

src/components/Doctors/MapEvents.js, src/context/filterContext.js
=> Search by institution

public/index.html, src/components/Doctors/Map.js, src/components/Shared/Leaflet/Markers.js, src/components/Shared/Leaflet/index.js
=> Don't reference external CSS and JS from unpkg.com

src/pages/Doctor.js
=> Use doctor type when finding doctor for doctor's page 🐛

src/components/DoctorCard/Info.js, src/components/DoctorCard/styles/index.js, src/components/Doctors/index.js, src/components/Doctors/styles/index.js, src/components/Filters/Search.js, src/components/Filters/styles/Search.js, src/components/Header/index.js, src/components/Header/styles/index.js, src/components/Shared/FooterInfo.js, src/components/Shared/Loader.js, src/pages/About.js, src/pages/Doctor.js, src/pages/Faq/index.js, src/pages/Home.js, src/pages/styles/Doctor.js, src/pages/styles/Home.js, src/pages/styles/Markdown.js
Fix:
- loader causing overflow
- infinite scroll on Home page overflows
- hide footer if no doctor's card on Home page
- on very small mobile filters in 3 lines
- some browser errors
- Faq page styling (ios summary tag marker, answer first paragraph)
=> UI improvements and fixes - attempt 2

src/services/doctors.js
Add search by part of municipality (mestne četrti, krajevne skupnosti, vaške četrti) where available.
Examples: bežigrad, črnuče, magdalena...
We could also add search by `statisticalRegion`s, but am not sure if that would bring that much added value.
Prior changes:
* https://github.com/sledilnik/zdravniki-data/commit/846a74214465236f96e4654dc6401ded613a6ebf
* https://github.com/sledilnik/zdravniki-data/commit/a2802bef433344b1170cf4ba71333ef98f453222
* https://github.com/sledilnik/zdravniki-data/commit/a8432c159f1949b7ee3a7c2cf696c96f70b4ff3a
=> Add search by municipalityPart 🎯 

src/components/DoctorCard/Info.js, src/components/DoctorCard/ReportError/index.js, src/components/DoctorCard/styles/index.js, src/components/Doctors/Markers.js, src/components/Doctors/styles/index.js, src/components/Header/index.js, src/index.css, src/routes/index.js
=> Improved tooltip

src/components/DoctorCard/index.js, src/components/DoctorCard/styles/index.js, src/components/Doctors/index.js, src/components/Doctors/styles/index.js
only mobile view (down md)
before:
map & cards are un-mounted when switching between views.
after:
use css (opacity) to show different view
! zIndex must change -> map events issue (not quite sure about it)
=> fix(Home): 💄 zoom and filter state lost

src/components/DoctorCard/Info.js, src/components/DoctorCard/PageInfo.js
=> Mobile tooltip timeouts

src/components/DoctorCard/Info.js, src/components/DoctorCard/index.js, src/pages/Doctor.js, src/services/doctors.js
To hopely avoid sluggish :smirk: performance.
Slugifying could also be optimized in ReportError, but that is not called so many times as comparing during search
=> ⚡ Only slugify once instead of at every search keypress

src/components/DoctorCard/ReportError/index.js, src/const/csvURL.js, src/const/doctors.js, src/context/doctorsContext.js, src/context/filterContext.js, src/pages/Doctor.js, src/services/doctors.js
It looks ok but please double check.
Fixes #147
=> Fix: Remove request dict-doctors.csv

src/locales/sl.json
"Ker" morda ni najboljši, ampak če ga pustimo, pred njim definitivno manjka vejica.
"kot" ni narobe, se mi pa "od" sliši bolje.
=> Add missing comma

src/components/DoctorCard/Info.js, src/components/DoctorCard/PageInfo.js, src/components/DoctorCard/Shared/Links.js, src/components/DoctorCard/Shared/PageInfoPhones.js, src/components/DoctorCard/Shared/PhoneButton.js, src/components/DoctorCard/Shared/index.js, src/components/DoctorCard/styles/PageInfo.js, src/components/DoctorCard/styles/index.js, src/components/Doctors/styles/index.js
=> Rebased suppport multiple phone nums

src/components/DoctorCard/Info/index.js, src/components/DoctorCard/PageInfo/index.js, src/components/DoctorCard/Shared/Tooltips.js, src/const/csvURL.js, src/context/doctorsContext.js, src/locales/en.json, src/locales/sl.json, src/services/doctors.js
Partially fixes #148.
It should use new location, accepts_override, availability_override, etc.
Add note_override, date_override, email, orderform to doctor page. Needs styling.
=> Use doctor overrides

src/components/DoctorCard/Info/index.js, src/components/DoctorCard/PageInfo/index.js, src/components/DoctorCard/ReportError/index.js, src/pages/Doctor.js, src/routes/index.js, src/services/doctors.js
=> Add insititution ID in path of doctor URL

src/components/Doctors/index.js, src/components/Shared/Loader.js, src/locales/en.json, src/locales/sl.json
- added alert msg when no doctors are found
- added loading animation for the cards list.
Please check the msg text.
=> No results msg

src/content/en/about.md, src/content/sl/about.md
=> FIX: About page formatting issue caused by using hyphen instead of dash

src/components/Shared/ScrollTop.js
@jalezi if you like, you can merge this as well
=> Smooth scroll top

src/components/Filters/styles/Search.js, src/components/Filters/styles/index.js
=> Mobile seach gap

src/components/DoctorCard/Info/index.js, src/components/DoctorCard/PageInfo/index.js, src/components/DoctorCard/Shared/Tooltips.js, src/components/DoctorCard/Shared/index.js, src/components/DoctorCard/styles/PageInfo.js, src/components/DoctorCard/styles/index.js, src/components/Shared/CircleChart/index.js, src/const/doctors.js, src/services/doctors.js
=> List add xtra clinic badge + remove accessibility % and add extra circle chart for over 100%

src/components/DoctorCard/Info/index.js
Fixes: https://github.com/sledilnik/zdravniki/issues/153
=> Cmd + Click should open in new tab

src/services/doctors.js
Simple fix. If neither doctor or institution has geo location, use center of Slovenia.
=> fix: neither doc or inst has lat, lng

src/assets/icon-tw-new-rounded.svg, src/components/Shared/Icons.js
Changes old twitter logo with new 'x' logo.
=> fix: 🩹 replace old tw icon with new

.github/workflows/pr-cleanup.yml, .github/workflows/pr.yml, .github/workflows/prod.yml, .github/workflows/stage.yml
`ubuntu-latest` is currently alias for `ubuntu-22.04`
See https://github.com/actions/runner-images#available-images
=> Use latest ubuntu 22.04 runner instead of 20.04

src/i18n.js, src/locales/hr.json
Translation:  [![Stanje prevoda](https://hosted.weblate.org/widgets/sledilnik/hr/zdravniki/svg-badge.svg)](https://hosted.weblate.org/projects/sledilnik/zdravniki/hr/)
https://hosted.weblate.org/projects/sledilnik/zdravniki/hr/
Needs finishing and review.
Preview: https://pr-446.zdravniki.sledilnik.org/hr/
cc @vekejsn 
Related:
* #193 
* #208
=> i18n: Enabled Croatian translation

.github/workflows/playwright.yml, .gitignore, README.md, package.json, playwright.config.js, src/tests/e2e/routing.spec.js, yarn.lock
Adds simple tests to check if html lang attr had proper value.
Library: [Playwright](https://playwright.dev/docs)
TODO: [CI GitHub Actions](https://playwright.dev/docs/ci-intro); help needed :)
=> test: ✅ adds first E2E tests

src/content/en/about.md, src/content/sl/about.md
Regular "-" is for an unordered list.
@SterArcher There is a slight difference between "-" but "—", hard to notice with naked 👁️.
FIX: #469
=> fix: 🩹 wrong hyphens in md unordered list

src/locales/en.json
Weighted person quotient is a wrong term for glavarina, Capitation is the correct one
=> Fix Weighted person quotient to Capitation

src/locales/en.json
Add taskD.dropdownLabel en translation.
=> en.json: add dropdownLabel
